image: node:latest

stages:
    - build
    - deploy


.changes: &changes
    - public/**/*
    - src/**/*
    - '*.config.*'
    - index.html
    - package.json
    - tsconfig*.json
    - yarn.lock
    - .gitlab-ci.yml
    - .prettier*

build:
    stage: build
    cache:
        - key:
            prefix: $CI_MERGE_REQUEST_IID
            files:
                - yarn.lock
          paths:
              - node_modules/
              - .yarn/install-state.gz
    script:
        - corepack enable
        - corepack install --global yarn@stable
        - YARN_CHECKSUM_BEHAVIOR=update yarn install
        - yarn run lint
        - yarn run check
        - yarn run smui
        - yarn run build
        - yarn run test -- --run
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes: *changes
        - if: $CI_MERGE_REQUEST_ID
          changes: *changes
    artifacts:
        paths: ['dist']

pages:
    image: alpine:latest
    stage: deploy
    dependencies:
        - build
    script:
        - echo Deploying to Pages
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes: *changes
    artifacts:
        paths: ['dist']
    publish: dist
