image: node:latest

stages:
    - deploy

cache:
    - key:
          files:
              - yarn.lock
      paths:
          - node_modules/
          - .yarn/install-state.gz

.changes: &changes
    - src/**/*
    - '*.config.*'
    - index.html
    - package.json
    - tsconfig*.json
    - yarn.lock
    - .gitlab-ci.yml
    - .prettier*

pages:
    stage: deploy
    script:
        - corepack enable
        - corepack install --global yarn@stable
        - YARN_CHECKSUM_BEHAVIOR=update yarn install
        - yarn run lint
        - yarn run check
        - yarn run smui
        - yarn run build
        - yarn run test -- --run
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes: *changes
        - if: $CI_MERGE_REQUEST_ID
          changes: *changes
    artifacts:
        paths: ['dist']
    publish: dist
