image: node:latest

stages:
    - install_lint_build
    - deploy

cache:
    paths:
        - node_modules/
        - .yarn/
        - .cache/
        - dist/
        - smui/

.changes: &changes
    - src/**/*
    - '*.config.*'
    - index.html
    - package.json
    - tsconfig*.json
    - yarn.lock
    - .gitlab-ci.yml
    - .prettier*

install_lint_build:
    stage: install_lint_build
    script:
        - corepack enable
        - corepack install --global yarn@stable
        - yarn install --immutable --check-cache --check-resolutions
        - yarn run lint
        - yarn run check
        - yarn run smui
        - yarn run build
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes: *changes
        - if: $CI_MERGE_REQUEST_ID
          changes: *changes

pages:
    stage: deploy
    image: alpine:latest
    script:
        - echo 'Deploying...'
    artifacts:
        paths: ['dist']
    publish: dist
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes: *changes
